### ISSUE TITLE
Add Support for Geeklog's demo mode

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/recaptcha#5]
Add support for Geeklog's demo mode as we don't want the recaptcha plugin disabled or uninstalled. 

For example in the function plugin_autouninstall_recaptcha we could add at the beginning:
`
if (isset($_CONF['demo_mode']) && $_CONF['demo_mode']) {
  return "";
}
`

We also don't want some the Config options for reCaptcha to be changed in demo mode. I have already added those to Geeklog. (needs to be tested to confirmed disabled)

**Comment by mystralkk** [comment]
Implemented with change set 76f1b27.
